package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;
import frc.robot.RobotContainer;
import java.util.Optional;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.util.PathPlannerLogging;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.FunctionalCommand;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import org.littletonrobotics.junction.Logger;

import edu.wpi.first.math.system.plant.DCMotor;
import org.ironmaple.simulation.drivesims.AbstractDriveTrainSimulation;

import frc.robot.Constants;
import frc.robot.FieldConstants;
import frc.robot.POI;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.vision.Vision;
import frc.robot.utility.TrajectoryErrorTracker;
import frc.robot.utility.simulation.MapleSimSwerveDrivetrain;

@SuppressWarnings("unused")

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    // 5 ms (200 Hz). This drives BOTH the notifier and maple-sim's SimulatedArena timing. It must stay
    // well below the 20 ms main-loop period: the steer gains regulateModuleConstantsForSimulation()
    // installs (kP=70) go numerically unstable at 20 ms, diverging at gain ~= -2 and flinging the pose.
    // Matches Team 254's reference integration; maple-sim's own default is 250 Hz.
    private static final double kSimLoopPeriod = 0.005;
    private Notifier m_simNotifier = null;
    private SwerveModuleConstants<?, ?, ?>[] moduleConstantsForSim;
    private MapleSimSwerveDrivetrain mapleSim;
    private Alliance m_lastAppliedAlliance;

    // Nullable: RobotContainer constructs this drivetrain before it can construct the tracker
    // (which needs this drivetrain's pose supplier), so the reference arrives after
    // configureAutoBuilder() has already registered the PathPlannerLogging callbacks below.
    // Set once via setTrajectoryErrorTracker(); guarded at each call site until then.
    private TrajectoryErrorTracker trajectoryErrorTracker;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    public void setSysIdRoutine(SysIdRoutine routine) {
        m_sysIdRoutineToApply = routine;
    }

    public void useTranslationSysId() {
        m_sysIdRoutineToApply = m_sysIdRoutineTranslation;
    }

    public void useSteerSysId() {
        m_sysIdRoutineToApply = m_sysIdRoutineSteer;
    }

    public void useRotationSysId() {
        m_sysIdRoutineToApply = m_sysIdRoutineRotation;
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
        moduleConstantsForSim = modules;
        logCancoderBootReadings();
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency,
                MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
        moduleConstantsForSim = modules;
        logCancoderBootReadings();
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
        moduleConstantsForSim = modules;
        logCancoderBootReadings();
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * CANcoder boot barrier: blocks construction (real hardware only) until every module's
     * CANcoder has published a fresh absolute reading over the CAN bus, then logs each
     * module's first reading so startup state is auditable against the TunerConstants
     * offsets. The magnet offsets themselves are applied inside super() by the generated
     * SwerveDrivetrain -- this cannot run earlier without leaving the generated flow, but
     * it guarantees no code after construction ever sees a stale/cached absolute position.
     */
    private void logCancoderBootReadings() {
        // Sim CANcoders are driven by the maple-sim thread, which hasn't started yet at
        // construction time -- a blocking wait here would stall desktop startup on signals
        // that never arrive. Real readings only.
        if (Utils.isSimulation()) {
            return;
        }

        final String[] moduleLabels = { "FL", "FR", "BL", "BR" };
        BaseStatusSignal[] absoluteSignals = new BaseStatusSignal[moduleLabels.length];
        for (int i = 0; i < moduleLabels.length; i++) {
            absoluteSignals[i] = getModule(i).getEncoder().getAbsolutePosition();
        }

        var status = BaseStatusSignal.waitForAll(1.5, absoluteSignals);
        if (!status.isOK()) {
            DriverStation.reportWarning(
                    "CANcoder boot barrier: no fresh data within 1.5 s (" + status
                            + "); readings below may be stale.",
                    false);
        }

        for (int i = 0; i < moduleLabels.length; i++) {
            double rotations = absoluteSignals[i].getValueAsDouble();
            int deviceId = getModule(i).getEncoder().getDeviceID();
            System.out.printf(
                    "CANcoder boot read %s (id %d): %.12f rot [%s]%n",
                    moduleLabels[i], deviceId, rotations, absoluteSignals[i].getStatus());
            Logger.recordOutput("Drive/CancoderBootReadRotations/" + moduleLabels[i], rotations);
        }
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                    () -> getState().Pose, // Supplier of current robot pose
                    this::resetPose, // Consumer for seeding pose against auto
                    () -> getState().Speeds, // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                            m_pathApplyRobotSpeeds
                                    .withSpeeds(speeds)
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            // PID constants for translation
                            new PIDConstants(5, 0, 0),
                            // PID constants for rotation
                            new PIDConstants(3, 0, 0)),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the
                    // case
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                    this // Subsystem for requirements
            );

        } catch (Exception ex) {
            DriverStation.reportError(
                    "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
        // Logs poses from auto
        PathPlannerLogging.setLogActivePathCallback(
                (activePath) -> {
                    Logger.recordOutput(
                            "Odometry/Trajectory", activePath.toArray(new Pose2d[activePath.size()]));
                    if (trajectoryErrorTracker != null) {
                        trajectoryErrorTracker.onActivePath(activePath);
                    }
                });
        PathPlannerLogging.setLogTargetPoseCallback(
                (targetPose) -> {
                    Logger.recordOutput("Odometry/TrajectorySetpoint", targetPose);
                    if (trajectoryErrorTracker != null) {
                        trajectoryErrorTracker.onTargetPose(targetPose);
                    }
                });
    }

    /**
     * Wires this drivetrain's PathPlannerLogging callbacks to also feed the tracker. Called once
     * by RobotContainer after both this drivetrain and the tracker exist -- the tracker cannot be
     * constructed until it has this drivetrain's pose supplier, so it necessarily postdates
     * configureAutoBuilder()'s callback registration above.
     */
    public void setTrajectoryErrorTracker(TrajectoryErrorTracker trajectoryErrorTracker) {
        this.trajectoryErrorTracker = trajectoryErrorTracker;
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    private static final double kAlignTolerance = 0.20;
    private static final double kAlignRotationTolerance = Math.toRadians(1);
    private static final double kAlignMaxSpeed = 0.5 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
    private static final double kAlignMaxRotationalSpeed = RotationsPerSecond.of(0.75).in(RadiansPerSecond);

    /** Drives to and holds a field point-of-interest, ported from the old AutoAlignPOI command. */
    public Command driveToPOI(POI targetPOI) {
        SwerveRequest.FieldCentric request = new SwerveRequest.FieldCentric()
                .withDriveRequestType(DriveRequestType.OpenLoopVoltage);
        PIDController x = new PIDController(1, 0, 0);
        PIDController y = new PIDController(1, 0, 0);
        PIDController rot = new PIDController(3, 0, 0);
        x.setTolerance(kAlignTolerance);
        y.setTolerance(kAlignTolerance);
        rot.setTolerance(kAlignRotationTolerance);
        rot.enableContinuousInput(-Math.PI, Math.PI);

        return new FunctionalCommand(
                () -> {},
                () -> {
                    Translation2d target = targetPOI.get();
                    Translation2d current = getState().Pose.getTranslation();
                    Translation2d vectorToHub = target.minus(current);
                    Translation2d opVector = new Translation2d(
                            vectorToHub.getX() * getOperatorForwardDirection().getCos()
                                    + vectorToHub.getY() * getOperatorForwardDirection().getSin(),
                            -vectorToHub.getX() * getOperatorForwardDirection().getSin()
                                    + vectorToHub.getY() * getOperatorForwardDirection().getCos());

                    double vx = MathUtil.clamp(x.calculate(0, opVector.getX()), -kAlignMaxSpeed, kAlignMaxSpeed);
                    double vy = MathUtil.clamp(y.calculate(0, opVector.getY()), -kAlignMaxSpeed, kAlignMaxSpeed);

                    double currentRotation = getState().Pose.getRotation().getRadians();
                    double targetRotation = targetPOI.getTargetRotation().getRadians();
                    double rotError = MathUtil.angleModulus(targetRotation - currentRotation);
                    double dxRotRadiansPerSecond = rot.calculate(currentRotation, currentRotation + rotError);
                    double dxRot = MathUtil.clamp(
                            dxRotRadiansPerSecond / (2 * Math.PI), -kAlignMaxRotationalSpeed, kAlignMaxRotationalSpeed);

                    setControl(
                            request
                                    .withVelocityX(MetersPerSecond.of(vx))
                                    .withVelocityY(MetersPerSecond.of(vy))
                                    .withRotationalRate(dxRot));
                },
                interrupted -> idle(),
                () -> {
                    boolean atPos = getState().Pose.getTranslation().getDistance(targetPOI.get()) < kAlignTolerance;
                    boolean atRot = Math.abs(MathUtil.angleModulus(
                            getState().Pose.getRotation().getRadians()
                                    - targetPOI.getTargetRotation().getRadians())) < kAlignRotationTolerance;
                    return atPos && atRot;
                },
                this);
    }

    private static final double kTrackHeadingToleranceRad = Math.toRadians(2.0);

    /** Rotates to face the hub (from Vision's AprilTag-layout-averaged position) while driving. Ported from Target. */
    public Command trackHub(Vision vision, double maxSpeed, DoubleSupplier xSupplier, DoubleSupplier ySupplier,
            boolean finishOnAlign) {
        return trackTarget(vision::getHubPosition, maxSpeed, xSupplier, ySupplier, finishOnAlign);
    }

    /** Rotates to face the pass target while driving. Ported from Target. */
    public Command trackPassTarget(Vision vision, double maxSpeed, DoubleSupplier xSupplier, DoubleSupplier ySupplier,
            boolean finishOnAlign) {
        return trackTarget(vision::getPassTargetPosition, maxSpeed, xSupplier, ySupplier, finishOnAlign);
    }

    private Command trackTarget(Supplier<Optional<Translation2d>> targetSupplier, double maxSpeed,
            DoubleSupplier xSupplier, DoubleSupplier ySupplier, boolean finishOnAlign) {
        PIDController headingPID = new PIDController(5.0, 0.0, 0.15);
        headingPID.enableContinuousInput(-Math.PI, Math.PI);
        SwerveRequest.FieldCentric driveReq = new SwerveRequest.FieldCentric()
                .withDriveRequestType(DriveRequestType.Velocity);

        return new FunctionalCommand(
                () -> {
                    headingPID.reset();
                    double currentHeading = getState().Pose.getRotation().getRadians();
                    headingPID.calculate(currentHeading, currentHeading);
                },
                () -> {
                    Optional<Translation2d> targetOpt = targetSupplier.get();
                    if (targetOpt.isEmpty()) {
                        setControl(new SwerveRequest.Idle());
                        return;
                    }

                    Pose2d robotPose = getState().Pose;
                    double target = trackingAngle(targetOpt.get(), robotPose);
                    double rotationOutput = headingPID.calculate(robotPose.getRotation().getRadians(), target);

                    double vx = -ySupplier.getAsDouble() * maxSpeed;
                    double vy = -xSupplier.getAsDouble() * maxSpeed;

                    setControl(
                            driveReq
                                    .withDriveRequestType(DriveRequestType.Velocity)
                                    .withVelocityX(vx)
                                    .withVelocityY(vy)
                                    .withRotationalRate(rotationOutput));
                },
                interrupted -> setControl(new SwerveRequest.Idle()),
                () -> {
                    if (!finishOnAlign) {
                        return false;
                    }
                    Optional<Translation2d> targetOpt = targetSupplier.get();
                    if (targetOpt.isEmpty()) {
                        return false;
                    }
                    Pose2d robotPose = getState().Pose;
                    double target = trackingAngle(targetOpt.get(), robotPose);
                    double error = Math.abs(MathUtil.angleModulus(robotPose.getRotation().getRadians() - target));
                    return error < kTrackHeadingToleranceRad;
                },
                this);
    }

    private static double trackingAngle(Translation2d targetPos, Pose2d robotPose) {
        double offsetDeg = SmartDashboard.getNumber("offset", 0);
        Translation2d toTarget = targetPos.minus(robotPose.getTranslation());
        return toTarget.getAngle().getRadians() + Math.toRadians(offsetDeg);
    }

    @Override
    public void periodic() {

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        // Guarded so setOperatorPerspectiveForward only fires on an actual alliance change, not every
        // periodic() tick while disabled -- DriverStation.getAlliance() can flip/settle over several
        // ticks after a DS reconnect, and re-applying on every tick caused a spurious mid-match pi
        // reference flip. This entire block runs on the main robot thread only (Subsystem.periodic());
        // do not move any of this logic into m_simNotifier or any other background thread.
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                if (allianceColor != m_lastAppliedAlliance) {
                    setOperatorPerspectiveForward(
                            allianceColor == Alliance.Red
                                    ? kRedAlliancePerspectiveRotation
                                    : kBlueAlliancePerspectiveRotation);
                    m_lastAppliedAlliance = allianceColor;

                    // Sim-only auto-spawn. This is the earliest point the alliance is actually
                    // knowable -- getAlliance() is empty during construction (the DS hasn't
                    // connected yet), so spawning in startSimThread() would always get the fallback.
                    // resetPose() seeds both the odometry and the maple-sim physics world. The
                    // enclosing block only runs while disabled (or before the first apply), so this
                    // can never yank the robot mid-drive.
                    if (mapleSim != null) {
                        Pose2d spawnPose = FieldConstants.middleStartFor(allianceColor);
                        resetPose(spawnPose);
                        Logger.recordOutput("Drivetrain/SimSpawnPose", spawnPose);
                    }
                }
                m_hasAppliedOperatorPerspective = true;
            });
        }
        // Logged every cycle (not just on a flip) so the topic exists in the log browser from tick 1 --
        // "None" until the alliance first resolves, then steps to "Red"/"Blue" exactly at a flip.
        Logger.recordOutput("Vision/PerspectiveFlip",
                m_lastAppliedAlliance == null ? "None" : m_lastAppliedAlliance.toString());
        if (DriverStation.isDisabled()) {
            Logger.recordOutput("SwerveStates/Setpoints", new SwerveModuleState[] {});
        }

    }

    private void startSimThread() {
        // TODO: confirm actual drive/steer motors -- assumed Kraken X60
        mapleSim = new MapleSimSwerveDrivetrain(
                Seconds.of(kSimLoopPeriod),
                Kilograms.of(Constants.kRobotMassWithBumpersKg),
                Meters.of(Constants.kBumperLengthXMeters),
                Meters.of(Constants.kBumperWidthYMeters),
                DCMotor.getKrakenX60(1),
                DCMotor.getKrakenX60(1),
                Constants.kWheelCOF,
                getModuleLocations(),
                getPigeon2(),
                getModules(),
                moduleConstantsForSim);

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(mapleSim::update);
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    @Override
    public void resetPose(Pose2d pose) {
        super.resetPose(pose);
        if (mapleSim != null) {
            mapleSim.mapleSimDrive.setSimulationWorldPose(pose);
        }
    }

    /** Returns the maple-sim drivetrain simulation, or null on real hardware / before the sim thread starts. */
    public AbstractDriveTrainSimulation getMapleSimDrive() {
        return mapleSim == null ? null : mapleSim.mapleSimDrive;
    }

    /**
     * Returns the physics simulation's ground-truth pose, or null on real hardware / before the sim
     * thread starts. Unlike getState().Pose (the Kalman-filtered estimate vision measurements are
     * fused into), this is independent of vision entirely -- safe to use as a vision-sim ground truth
     * source without creating a self-referential feedback loop.
     */
    public Pose2d getSimulatedGroundTruthPose() {
        return mapleSim == null ? null : mapleSim.mapleSimDrive.getSimulatedDriveTrainPose();
    }

    /**
     * Raw Pigeon 2 yaw in degrees, independent of the vision-fused pose estimate. Safe to feed into
     * MegaTag2's SetRobotOrientation -- unlike getState().Pose.getRotation(), this value is never
     * itself corrected by a vision measurement, so it can't create a self-referential feedback loop.
     */
    public double getRawGyroYawDegrees() {
        return getPigeon2().getYaw().getValueAsDouble();
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
